---
# NFS Specific Mount Points
- block:
    - name: Create mount points for NFS file systems
      file:
        state=directory
        path="/{{ item }}"
      become: true
      with_items:
        - '{{ ora_volumes_nfs }}'
      tags:
        - cre_mount_points

    - name: Mount NFS file systems on Oracle hosts
      mount:
        path: "/{{ item }}"
        src: "{{ svm_mgmt_nfs_lif }}:/{{ item }}"
        fstype: nfs
        opts: "rw,bg,hard,nointr,rsize=32768,wsize=32768,tcp,vers=3,timeo=600"
        state: mounted
      become: true
      with_items:
          - '{{ ora_volumes_nfs }}'
      tags:
        - mount_nfs_volumes
