---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create SVM NFS Export Policy Rules
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Create ora svm nfs export policy rules
      na_ontap_export_policy_rule:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        vserver: "{{ svm_name }}"
        policy_name: "{{ nfs_exp_policy }}"
        client_match: "{{ client_match }}"
        protocol: "{{ data_protocol }}"
        ro_rule: sys
        rw_rule: sys
        super_user_security: sys
        allow_suid: true
        https: true
        validate_certs: false
      tags:
        - ontap_export_policy_rule

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Add NFS Export Policy to the root volume 
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Add ora svm nfs export policy to the root volume
      na_ontap_volume:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        name: "{{ svm_name }}_root"
        policy: "{{ nfs_exp_policy }}"
        vserver: "{{ svm_name }}"
        https: true
        validate_certs: false
      tags:
        - ontap_export_policy_apply

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
