---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Flexvols for NFS
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Create FlexVols for nfs Oracle database
      na_ontap_volume:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        vserver: "{{ svm_name }}"
        policy: "{{ nfs_exp_policy }}"
        name: "{{ item.vol_name }}"
        aggregate_name: "{{ item.aggr_name }}"
        size: "{{ item.size }}"
        is_online: True
        space_guarantee: none
        percent_snapshot_space: 0
        junction_path: "/{{ item.vol_name }}"
        https: true
        validate_certs: false
      with_items:
        - "{{ volumes_nfs }}"
      tags:
        - ontap_flexvol_create

# ----------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------- 
